### ISSUE TITLE
Error in { : task 1 failed - "'breaks' are not unique"

### ISSUE THREAD

**Issue by CarlesUPV** [guillaumeevin/GWEX#2]
Good Evening,

The error - Error in { : task 1 failed - "'breaks' are not unique" - is appearing when simulating using the option "is3Damount=T". It looks to me that the problem has something to do with the dissaggregator, maybe when applying the function cut, but my R programming knowledge does not reach to understand what is the problem looking into the master code. Any ideas on the reason? Thanks

[GWEX_breaks_issue.zip](https://github.com/guillaumeevin/GWEX/files/6031152/GWEX_breaks_issue.zip)

**Comment by guillaumeevin** [comment]
Dear Carles,

Sorry for this very late answer, it seems that I do not receive any notification when an issue is raised. I had a look at the bug and the problem comes from the disaggregation from 3-day prec. to 1-day prec. that applies different patterns according to the classes of intensity. To compute these classes, I use an argument prob.class in the function simGwexModel, which is used to define the different probabilities. The default probabilities are c(0.5, 0.75, 0.9, 0.99) and in your case, the quantile 0.5 was 0 for the first season, which was causing a problem because I also put a lower bound of zero to "cut" the series into different subsets of similar intensities. As the "cut" function in R does not accept redundant values for the argument "breaks", the code crashes.

The solution, in that case, is to change prob.class when the function simGwexModel is called.

However, I agree that this can often happen and maybe I should send an error message which clarifies the problem.
